services:
  # Database
  - type: database
    name: book-buddy-db
    databaseName: book_buddy_db_jtrt
    user: book_buddy_db_jtrt_user
    plan: free

  # Backend API
  - type: web
    name: book-app-server
    env: go
    buildCommand: make build
    startCommand: make migrate && make start
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: book-buddy-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        fromService:
          type: static
          name: book-app-web-client
          property: url
      - key: SECURE_COOKIES
        value: true
      - key: AUTH0_DOMAIN
        sync: false
      - key: AUTH0_CLIENT_ID
        sync: false
      - key: AUTH0_CLIENT_SECRET
        sync: false
      - key: AUTH0_AUDIENCE
        sync: false


  # Frontend Web Client
  - type: static
    name: book-app-web-client
    env: static
    rootDir: web-client
    buildCommand: node generate-config.mjs
    staticPublishPath: .
    plan: free
    envVars:
      - key: API_BASE_URL
        fromService:
          type: web
          name: book-app-server
          property: url
      - key: AUTH0_DOMAIN
        sync: false
      - key: AUTH0_CLIENT_ID
        sync: false
