// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package query

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type BookStatus string

const (
	BookStatusOwned      BookStatus = "owned"
	BookStatusWishlisted BookStatus = "wishlisted"
	BookStatusRemoved    BookStatus = "removed"
)

func (e *BookStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BookStatus(s)
	case string:
		*e = BookStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BookStatus: %T", src)
	}
	return nil
}

type NullBookStatus struct {
	BookStatus BookStatus `json:"book_status"`
	Valid      bool       `json:"valid"` // Valid is true if BookStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBookStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BookStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BookStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBookStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BookStatus), nil
}

type Book struct {
	ID        uuid.UUID      `json:"id"`
	Isbn      string         `json:"isbn"`
	Title     string         `json:"title"`
	Author    string         `json:"author"`
	CoverUrl  sql.NullString `json:"cover_url"`
	CreatedAt time.Time      `json:"created_at"`
}

type RemovalReason struct {
	ID         uuid.UUID `json:"id"`
	UserBookID uuid.UUID `json:"user_book_id"`
	Reason     string    `json:"reason"`
	CreatedAt  time.Time `json:"created_at"`
}

type User struct {
	ID               uuid.UUID `json:"id"`
	Email            string    `json:"email"`
	CreatedAt        time.Time `json:"created_at"`
	ExternalID       string    `json:"external_id"`
	ExternalProvider string    `json:"external_provider"`
}

type UserBook struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	BookID    uuid.UUID  `json:"book_id"`
	Status    BookStatus `json:"status"`
	CreatedAt time.Time  `json:"created_at"`
}
